import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* Header */}
      <body className={`${inter.className}`}>
        <main className='min-h-screen'>{children}</main>

        {/* Footer */}
        <footer className='bg-muted/50 py-12'>
          <div className='container mx-auto px-4 text-center text-gray-200'>
            Copyright &copy; 2025. Santosh Gurung
          </div>
        </footer>
      </body>
    </html>
  );
}
